// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCflAsXInmzFElCEFQuWeYpzsnb14O8GKU',
    appId: '1:549231023884:web:0e5e000cb99e73ebad5b29',
    messagingSenderId: '549231023884',
    projectId: 'my-offline-app-5e43f',
    authDomain: 'my-offline-app-5e43f.firebaseapp.com',
    storageBucket: 'my-offline-app-5e43f.firebasestorage.app',
    measurementId: 'G-8NX7YRQ3H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99vFfAHZLOurB-C4u19FifYV26rRSxFk',
    appId: '1:549231023884:android:b73332f8da4124b6ad5b29',
    messagingSenderId: '549231023884',
    projectId: 'my-offline-app-5e43f',
    storageBucket: 'my-offline-app-5e43f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJILdaYpog-tHoucPqyiWOfPzr9Yxlxo4',
    appId: '1:549231023884:ios:3f571528229dc180ad5b29',
    messagingSenderId: '549231023884',
    projectId: 'my-offline-app-5e43f',
    storageBucket: 'my-offline-app-5e43f.firebasestorage.app',
    iosBundleId: 'com.synapsis.haulerTruck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJILdaYpog-tHoucPqyiWOfPzr9Yxlxo4',
    appId: '1:549231023884:ios:3f571528229dc180ad5b29',
    messagingSenderId: '549231023884',
    projectId: 'my-offline-app-5e43f',
    storageBucket: 'my-offline-app-5e43f.firebasestorage.app',
    iosBundleId: 'com.synapsis.haulerTruck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCflAsXInmzFElCEFQuWeYpzsnb14O8GKU',
    appId: '1:549231023884:web:2ff8f859c5a6def9ad5b29',
    messagingSenderId: '549231023884',
    projectId: 'my-offline-app-5e43f',
    authDomain: 'my-offline-app-5e43f.firebaseapp.com',
    storageBucket: 'my-offline-app-5e43f.firebasestorage.app',
    measurementId: 'G-G0SLG64DC0',
  );

}